package com.bypassfuzzer.burp.ui.session;

import burp.api.montoya.http.message.requests.HttpRequest;
import com.bypassfuzzer.burp.core.urlvalidation.UrlValidationAttackSetting;
import com.bypassfuzzer.burp.core.urlvalidation.UrlValidationContext;
import com.bypassfuzzer.burp.core.urlvalidation.UrlValidationEncoding;
import com.bypassfuzzer.burp.http.ConfiguredHeader;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;

public class UrlValidationOptionsPanel extends JPanel {

    private static final int SECTION_NOTE_HEIGHT = 56;

    private final boolean collaboratorAvailable;
    private final JTextField markerTextField;
    private final JTextField allowedHostField;
    private final JTextField attackerHostField;
    private final JCheckBox collaboratorPayloadsCheckbox;
    private final JComboBox<String> attackerSchemeCombo;
    private final JCheckBox absoluteUrlFamilyCheckbox;
    private final JCheckBox hostnameFamilyCheckbox;
    private final JCheckBox corsFamilyCheckbox;
    private final JCheckBox domainAllowListBypassCheckbox;
    private final JCheckBox fakeRelativeUrlsCheckbox;
    private final JCheckBox loopbackCheckbox;
    private final JCheckBox ipv6Checkbox;
    private final JCheckBox cloudMetadataEndpointsCheckbox;
    private final JCheckBox urlSplittingUnicodeCheckbox;
    private final JCheckBox normalizationAttackCheckbox;
    private final JCheckBox encodingRawCheckbox;
    private final JCheckBox encodingIntrudersCheckbox;
    private final JCheckBox encodingEverythingCheckbox;
    private final JCheckBox encodingSpecialCharsCheckbox;
    private final JCheckBox encodingUnicodeEscapeCheckbox;
    private final ThrottleSettingsControl throttleControl;
    private final RequestHeadersControl requestHeadersControl;
    private long userAgentRandomizationSeed;

    public UrlValidationOptionsPanel(HttpRequest request, boolean collaboratorAvailable) {
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        this.collaboratorAvailable = collaboratorAvailable;

        String inferredHost = request.httpService() != null && request.httpService().host() != null
            ? request.httpService().host()
            : "";

        markerTextField = new JTextField("{INJECT}", 12);
        markerTextField.setToolTipText("Each occurrence of this marker in the request editor will be replaced with generated payloads");

        allowedHostField = new JTextField(inferredHost, 18);
        allowedHostField.setToolTipText("Trusted host to emulate during allowlist bypass testing");

        attackerHostField = new JTextField("127.0.0.1", 18);
        attackerHostField.setToolTipText("Host used in generated bypass payloads");
        collaboratorPayloadsCheckbox = new JCheckBox("Use collaborator payloads", false);
        collaboratorPayloadsCheckbox.setToolTipText("Replace the attacker host with a Burp Collaborator payload");
        if (!collaboratorAvailable) {
            collaboratorPayloadsCheckbox.setEnabled(false);
            collaboratorPayloadsCheckbox.setToolTipText("Burp Collaborator is not available. Requires Burp Suite Professional with Collaborator configured.");
        }
        collaboratorPayloadsCheckbox.addActionListener(e -> updateAttackerHostState());

        attackerSchemeCombo = new JComboBox<>(new String[]{"https", "http"});
        absoluteUrlFamilyCheckbox = new JCheckBox(UrlValidationContext.ABSOLUTE_URL.displayName(), true);
        hostnameFamilyCheckbox = new JCheckBox(UrlValidationContext.HOSTNAME.displayName(), false);
        corsFamilyCheckbox = new JCheckBox(UrlValidationContext.CORS_ORIGIN.displayName(), false);
        domainAllowListBypassCheckbox = new JCheckBox(UrlValidationAttackSetting.DOMAIN_ALLOW_LIST_BYPASS.displayName(), true);
        fakeRelativeUrlsCheckbox = new JCheckBox(UrlValidationAttackSetting.FAKE_RELATIVE_URLS.displayName(), true);
        loopbackCheckbox = new JCheckBox(UrlValidationAttackSetting.LOOPBACK.displayName(), true);
        ipv6Checkbox = new JCheckBox(UrlValidationAttackSetting.IPV6.displayName(), false);
        cloudMetadataEndpointsCheckbox = new JCheckBox(UrlValidationAttackSetting.CLOUD_METADATA_ENDPOINTS.displayName(), false);
        urlSplittingUnicodeCheckbox = new JCheckBox(UrlValidationAttackSetting.URL_SPLITTING_UNICODE_CHARACTERS.displayName(), false);
        normalizationAttackCheckbox = new JCheckBox(UrlValidationAttackSetting.NORMALIZATION_ATTACK.displayName(), false);
        normalizationAttackCheckbox.setToolTipText("Emit fullwidth / Unicode compatibility variants of the attacker and allowed hosts that NFKC-normalize back to ASCII.");
        encodingRawCheckbox = new JCheckBox(UrlValidationEncoding.RAW.label(), true);
        encodingIntrudersCheckbox = new JCheckBox(UrlValidationEncoding.INTRUDERS.label(), true);
        encodingEverythingCheckbox = new JCheckBox(UrlValidationEncoding.EVERYTHING.label(), false);
        encodingSpecialCharsCheckbox = new JCheckBox(UrlValidationEncoding.SPECIAL_CHARS.label(), true);
        encodingUnicodeEscapeCheckbox = new JCheckBox(UrlValidationEncoding.UNICODE_ESCAPE.label(), false);

        throttleControl = new ThrottleSettingsControl(ThrottleDefaults.forUrlValidation());
        requestHeadersControl = new RequestHeadersControl(this);

        add(createTargetingSection());
        add(Box.createVerticalStrut(10));
        add(createHostSection());
        add(Box.createVerticalStrut(10));
        add(createPayloadSection());
        add(Box.createVerticalStrut(10));
        add(createExecutionSection());
        add(Box.createVerticalGlue());
        updateAttackerHostState();
    }

    public String markerText() {
        return markerTextField.getText();
    }

    public String allowedHostText() {
        return allowedHostField.getText();
    }

    public String attackerHostText() {
        return attackerHostField.getText();
    }

    public String attackerScheme() {
        return (String) attackerSchemeCombo.getSelectedItem();
    }

    public boolean useCollaboratorPayloads() {
        return collaboratorPayloadsCheckbox.isSelected() && collaboratorPayloadsCheckbox.isEnabled();
    }

    public java.util.Set<UrlValidationContext> payloadFamilies() {
        java.util.LinkedHashSet<UrlValidationContext> families = new java.util.LinkedHashSet<>();
        if (absoluteUrlFamilyCheckbox.isSelected()) {
            families.add(UrlValidationContext.ABSOLUTE_URL);
        }
        if (hostnameFamilyCheckbox.isSelected()) {
            families.add(UrlValidationContext.HOSTNAME);
        }
        if (corsFamilyCheckbox.isSelected()) {
            families.add(UrlValidationContext.CORS_ORIGIN);
        }
        return java.util.Set.copyOf(families);
    }

    public java.util.Set<UrlValidationEncoding> encodings() {
        java.util.LinkedHashSet<UrlValidationEncoding> selected = new java.util.LinkedHashSet<>();
        if (encodingRawCheckbox.isSelected()) selected.add(UrlValidationEncoding.RAW);
        if (encodingIntrudersCheckbox.isSelected()) selected.add(UrlValidationEncoding.INTRUDERS);
        if (encodingEverythingCheckbox.isSelected()) selected.add(UrlValidationEncoding.EVERYTHING);
        if (encodingSpecialCharsCheckbox.isSelected()) selected.add(UrlValidationEncoding.SPECIAL_CHARS);
        if (encodingUnicodeEscapeCheckbox.isSelected()) selected.add(UrlValidationEncoding.UNICODE_ESCAPE);
        return java.util.Set.copyOf(selected);
    }

    public java.util.Set<UrlValidationAttackSetting> attackSettings() {
        java.util.LinkedHashSet<UrlValidationAttackSetting> settings = new java.util.LinkedHashSet<>();
        if (domainAllowListBypassCheckbox.isSelected()) {
            settings.add(UrlValidationAttackSetting.DOMAIN_ALLOW_LIST_BYPASS);
        }
        if (fakeRelativeUrlsCheckbox.isSelected()) {
            settings.add(UrlValidationAttackSetting.FAKE_RELATIVE_URLS);
        }
        if (loopbackCheckbox.isSelected()) {
            settings.add(UrlValidationAttackSetting.LOOPBACK);
        }
        if (ipv6Checkbox.isSelected()) {
            settings.add(UrlValidationAttackSetting.IPV6);
        }
        if (cloudMetadataEndpointsCheckbox.isSelected()) {
            settings.add(UrlValidationAttackSetting.CLOUD_METADATA_ENDPOINTS);
        }
        if (urlSplittingUnicodeCheckbox.isSelected()) {
            settings.add(UrlValidationAttackSetting.URL_SPLITTING_UNICODE_CHARACTERS);
        }
        if (normalizationAttackCheckbox.isSelected()) {
            settings.add(UrlValidationAttackSetting.NORMALIZATION_ATTACK);
        }
        return java.util.Set.copyOf(settings);
    }

    public String throttleStatusCodesText() {
        return throttleControl.throttleStatusCodesText();
    }

    public com.bypassfuzzer.burp.core.throttle.ThrottleSettings.Posture posture() {
        return throttleControl.posture();
    }

    public int concurrency() { return throttleControl.concurrency(); }

    public int perHostConcurrency() { return throttleControl.perHostConcurrency(); }

    public com.bypassfuzzer.burp.core.throttle.ThrottleSettings.PauseMode pauseMode() {
        return throttleControl.pauseMode();
    }

    public long fixedPauseMillis() { return throttleControl.fixedPauseMillis(); }

    public java.util.List<ConfiguredHeader> requestHeaders() {
        return requestHeadersControl.headers();
    }

    public com.bypassfuzzer.burp.http.UserAgentMode userAgentMode() {
        return requestHeadersControl.userAgentMode();
    }

    public long userAgentRandomizationSeed() {
        if (userAgentMode() == com.bypassfuzzer.burp.http.UserAgentMode.DISABLED) return 0L;
        if (userAgentRandomizationSeed == 0L) {
            userAgentRandomizationSeed = java.util.concurrent.ThreadLocalRandom.current().nextLong();
        }
        return userAgentRandomizationSeed;
    }

    public void setControlsEnabled(boolean enabled) {
        markerTextField.setEnabled(enabled);
        allowedHostField.setEnabled(enabled);
        attackerHostField.setEnabled(enabled && !useCollaboratorPayloads());
        collaboratorPayloadsCheckbox.setEnabled(enabled && collaboratorAvailable);
        attackerSchemeCombo.setEnabled(enabled);
        absoluteUrlFamilyCheckbox.setEnabled(enabled);
        hostnameFamilyCheckbox.setEnabled(enabled);
        corsFamilyCheckbox.setEnabled(enabled);
        domainAllowListBypassCheckbox.setEnabled(enabled);
        fakeRelativeUrlsCheckbox.setEnabled(enabled);
        loopbackCheckbox.setEnabled(enabled);
        ipv6Checkbox.setEnabled(enabled);
        cloudMetadataEndpointsCheckbox.setEnabled(enabled);
        urlSplittingUnicodeCheckbox.setEnabled(enabled);
        normalizationAttackCheckbox.setEnabled(enabled);
        encodingRawCheckbox.setEnabled(enabled);
        encodingIntrudersCheckbox.setEnabled(enabled);
        encodingEverythingCheckbox.setEnabled(enabled);
        encodingSpecialCharsCheckbox.setEnabled(enabled);
        encodingUnicodeEscapeCheckbox.setEnabled(enabled);
        throttleControl.setEnabled(enabled);
        requestHeadersControl.setEnabled(enabled);
    }

    private JPanel createTargetingSection() {
        JPanel panel = createSectionPanel("Targeting");
        panel.add(formRow("Marker", markerTextField, "place this in the request editor"));
        panel.add(sectionNote("Every marker in the request editor will be replaced by generated payloads."));
        return finalizeSection(panel);
    }

    private JPanel createHostSection() {
        JPanel panel = createSectionPanel("Hosts");
        panel.add(formRow("Allowed host", allowedHostField));
        panel.add(formRow("Attacker host", attackerHostField));
        panel.add(formRow("", collaboratorPayloadsCheckbox));
        panel.add(formRow("Scheme", attackerSchemeCombo));
        return finalizeSection(panel);
    }

    private void updateAttackerHostState() {
        attackerHostField.setEnabled(!useCollaboratorPayloads());
    }

    private JPanel createPayloadSection() {
        JPanel panel = createSectionPanel("Payloads");
        panel.add(checkboxRow("Families"));
        panel.add(attackSettingsRow("Attack settings"));
        panel.add(encodingCheckboxRow("Encodings"));
        return finalizeSection(panel);
    }

    private JPanel createExecutionSection() {
        JPanel panel = createSectionPanel("Execution");
        panel.add(formRow("Throttle", throttleControl.button(), "in-flight concurrency and rate-limit codes (pacing is automatic)"));
        panel.add(formRow("Request headers", requestHeadersControl.button(), "sent with every request"));
        return finalizeSection(panel);
    }

    private JPanel createSectionPanel(String title) {
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.setAlignmentX(Component.LEFT_ALIGNMENT);
        panel.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createTitledBorder(title),
            BorderFactory.createEmptyBorder(8, 8, 8, 8)
        ));
        return panel;
    }

    private JPanel finalizeSection(JPanel panel) {
        Dimension preferredSize = panel.getPreferredSize();
        panel.setMaximumSize(new Dimension(Integer.MAX_VALUE, preferredSize.height));
        return panel;
    }

    private JPanel formRow(String label, Component field) {
        return formRow(label, field, null);
    }

    private JPanel formRow(String label, Component field, String helperText) {
        JPanel row = new JPanel(new GridBagLayout());
        row.setAlignmentX(Component.LEFT_ALIGNMENT);

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(2, 0, 2, 6);
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;

        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0;
        row.add(new JLabel(label), gbc);

        gbc.gridx = 1;
        gbc.weightx = 1;
        row.add(field, gbc);

        if (helperText != null) {
            gbc.gridx = 1;
            gbc.gridy = 1;
            gbc.weightx = 1;
            gbc.insets = new Insets(0, 0, 2, 0);
            gbc.fill = GridBagConstraints.HORIZONTAL;
            gbc.anchor = GridBagConstraints.WEST;
            JTextArea helper = inlineNote(helperText);
            row.add(helper, gbc);
        }

        return row;
    }

    private JTextArea sectionNote(String text) {
        JTextArea note = new JTextArea(text);
        note.setAlignmentX(Component.LEFT_ALIGNMENT);
        note.setEditable(false);
        note.setFocusable(false);
        note.setLineWrap(true);
        note.setWrapStyleWord(true);
        note.setOpaque(false);
        note.setBorder(null);
        note.setFont(note.getFont().deriveFont(note.getFont().getStyle() | java.awt.Font.ITALIC, 11f));
        note.setMaximumSize(new Dimension(Integer.MAX_VALUE, SECTION_NOTE_HEIGHT));
        return note;
    }

    private JPanel checkboxRow(String label) {
        return checkboxListRow(label, absoluteUrlFamilyCheckbox, hostnameFamilyCheckbox, corsFamilyCheckbox);
    }

    private JPanel attackSettingsRow(String label) {
        return checkboxListRow(
            label,
            domainAllowListBypassCheckbox,
            fakeRelativeUrlsCheckbox,
            loopbackCheckbox,
            ipv6Checkbox,
            cloudMetadataEndpointsCheckbox,
            urlSplittingUnicodeCheckbox,
            normalizationAttackCheckbox
        );
    }

    private JPanel encodingCheckboxRow(String label) {
        return checkboxListRow(
            label,
            encodingRawCheckbox,
            encodingIntrudersCheckbox,
            encodingSpecialCharsCheckbox,
            encodingEverythingCheckbox,
            encodingUnicodeEscapeCheckbox
        );
    }

    private JPanel checkboxListRow(String label, JCheckBox... checkboxes) {
        JPanel row = new JPanel(new GridBagLayout());
        row.setAlignmentX(Component.LEFT_ALIGNMENT);

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(2, 0, 2, 6);
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;

        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0;
        gbc.anchor = GridBagConstraints.NORTHWEST;
        row.add(new JLabel(label), gbc);

        JPanel checkboxPanel = new JPanel();
        checkboxPanel.setLayout(new BoxLayout(checkboxPanel, BoxLayout.Y_AXIS));
        checkboxPanel.setAlignmentX(Component.LEFT_ALIGNMENT);
        for (JCheckBox checkbox : checkboxes) {
            checkbox.setAlignmentX(Component.LEFT_ALIGNMENT);
            checkboxPanel.add(checkbox);
        }

        gbc.gridx = 1;
        gbc.weightx = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        row.add(checkboxPanel, gbc);

        return row;
    }

    private JTextArea inlineNote(String text) {
        JTextArea note = sectionNote(text);
        note.setMaximumSize(new Dimension(Integer.MAX_VALUE, 32));
        return note;
    }

}
